apiVersion: apps/v1
kind: Deployment
metadata:
  name: neorent-api
  labels:
    app: neorent-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: neorent-api
  template:
    metadata:
      labels:
        app: neorent-api
    spec:
      containers:
      - name: neorent-api
        image: neorent-api:latest
        ports:
        - containerPort: 5000
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "5000"
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: uri
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: neorent-api-service
spec:
  selector:
    app: neorent-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  # Base64 encoded: mongodb://admin:admin@mongodb.neotech-consulting.com:27017/neorent?authSource=admin&ssl=true&tlsAllowInvalidCertificates=true
  uri: bW9uZ29kYjovL2FkbWluOmFkbWluQG1vbmdvZGIubmVvdGVjaC1jb25zdWx0aW5nLmNvbToyNzAxNy9uZW9yZW50P2F1dGhTb3VyY2U9YWRtaW4mc3NsPXRydWUmdGxzQWxsb3dJbnZhbGlkQ2VydGlmaWNhdGVzPXRydWU=